name: Flutter build APK

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    name: Run tests and build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JAVA 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17

      - name: Install Flutter version 3.35.1
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.1"

      - name: Install dependencies
        run: flutter pub get

      # - name: Run Tests
      # run: flutter test --coverage

      - name: Build APK
        run: flutter build apk --release

      - name: Send APK to Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          curl -F document=@build/app/outputs/flutter-apk/app-release.apk \
               -F chat_id="$TELEGRAM_CHAT_ID" \
               -F caption="New APK is ready!🚀" \
               "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendDocument"